//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string stu_id { get; set; }
        public string stu_name { get; set; }
        public string stu_sex { get; set; }
        public string teacher_id { get; set; }
        public string stu_tel { get; set; }
        public string course_name { get; set; }
        public string banji { get; set; }
    }
}
